In [1]:
# multidimenional indexing and axis in numpy
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr[0]

array([1, 2, 3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
  | | |
  12| 18
    15 

In [5]:
np.sum(arr,axis=0) # sum along rows (down each column)
# column wise sum

array([12, 15, 18])

[[1 2 3] -> 6
 [4 5 6]-> 15
 [7 8 9]] -> 24 

In [6]:
np.sum(arr, axis=1) # sum along column (across each row)
# row wise sum

array([ 6, 15, 24])

In [7]:
arr[0,1]

2

In [9]:
arr[0:2,1:3]
# 0:2 -> rows
# 1:3 -> 1 index and 2 index element

array([[2, 3],
       [5, 6]])

In [15]:
# 3d array
arr3d = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3d.shape # (depth , row, column)

(2, 2, 3)

In [17]:
# first sheet , second row, third column
#accssing elements in 3d
arr3d[0,1,2]

6

In [18]:
# get the first row from both sheets
arr3d[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [19]:
arr3d[0,0,:]

array([1, 2, 3])

In [21]:
# get all rows of the first column
first_col = arr[:,0]
first_col

array([1, 4, 7])

In [22]:
# get the first row from each "sheet" in a 3d array
first_row = arr3d[:,0,:]
first_row

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
# changing data along the axis
# replace all elements in column 1 with 0
arr[:,1] = 0
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])