In [1]:
import numpy as np

In [3]:
!pip install numpy

In [9]:
# 1d array
arr = np.array([1,2,3])

In [10]:
arr

array([1, 2, 3])

In [11]:
# 2d array
arr1 = np.array([[1,2,3],[4,5,6]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 3x3 array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 2x4 array of ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# 2x2 array filled with 7
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [16]:
# 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# [1,3,5,7,9] like range
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
# [o. 0.25 0.5 0.75 1.] evenly spaced
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [24]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
# array properties
myarr.shape # 5 rows and 3 columns

(5, 3)

In [26]:
myarr.size # total elements

15

In [28]:
myarr.ndim # dimensions 2d array -> 2

2

In [30]:
myarr.dtype # data type of array int64 or int32 on windows

dtype('int64')

In [35]:
# change data type in numpy array
# explicit type
arr2 = np.array([1,2,3,4,5], dtype='float32') #or np.float32

In [36]:
arr2

array([1., 2., 3., 4., 5.], dtype=float32)

In [37]:
# convert float to int 
arr_int = arr.astype(np.int32)
arr_int

array([1, 2, 3], dtype=int32)

In [41]:
# reshaping 
arr3 = np.array([[1,2,3],[4,5,6]])
arr3.shape

(2, 3)

In [42]:
reshape = arr3.reshape((3,2)) # change size
reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
#flattening Array
flattened = arr3.flatten() #convert 2d to 1d 
flattened

array([1, 2, 3, 4, 5, 6])