In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
result = []

#using loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result)

[1, 4, 9, 16, 25]


In [5]:
# fixing the loop problem
arr1 = np.array([1,2,3,4,5])
result = arr ** 2 # vectorized operation
print(result) 


[ 1  4  9 16 25]


Broadcasting: Scaling Arrays Without Extra Memory

Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies. It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.

In [7]:
result + 10 #Broadcasting: 10 is added to all elements

array([11, 14, 19, 26, 35])

In [10]:
# with two array
result1 = arr + arr1 # element wise addition
result1

array([ 2,  4,  6,  8, 10])

In [12]:
# with 2d and 1d 
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

result2 = a + b # broadasting arr2 across arr1

result2 # 1,2,3 is add in both sheets

array([[2, 4, 6],
       [5, 7, 9]])

In [14]:
# simulating a data set (5 samples, 3 features)
data = np.array([[10,20,30],
                 [15,25,35],
                 [20,30,40],
                 [25,35,45],
                 [30,40,50]])

#calculating mean and standard devaiation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

#normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)


[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
