In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [5]:
# to change the data type
arr.astype("float64")

array([1., 2., 3., 4.])

In [6]:
arr2 = np.array([11,12,122] , dtype = "float32")
arr2

array([ 11.,  12., 122.], dtype=float32)

In [10]:
#downcasting to save memory
arr_large = np.array([1000000,2000000,3000000], dtype = np.int64)

# Downcasting to a smaller dtype
arr_small = arr_large.astype(np.int32)


In [11]:
print(arr_small)

[1000000 2000000 3000000]


In [12]:
print(arr_small.dtype)

int32


In [20]:
#memory usage
arr_int64 = np.array([2,33,44], dtype = np.int64)
arr_int32 = np.array([11,22,33], dtype = np.int32)

In [21]:
arr_int64.nbytes # Output: 24 bytes (3 elements * 8 bytes each)

24

In [22]:
arr_int32.nbytes # Output: 12 bytes (3 elements * 4 bytes each)

12

In [25]:
arr3 = np.array(['apple','banana','cherry'], dtype = 'U10') # unicode string array
arr3

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [26]:
# complex number
arr4 = np.array([1+2j,3+4j,5+6j], dtype = 'complex128')
arr4

array([1.+2.j, 3.+4.j, 5.+6.j])

In [28]:
arr5 = np.array([{'a':1},[1,2,3]], dtype = 'object')

In [29]:
arr5

array([{'a': 1}, list([1, 2, 3])], dtype=object)