In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# indexing 
arr[0,1]

2

In [15]:
arr[-1,0]

10

In [16]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [17]:
arr1[0]

1

In [18]:
arr1[-1]

4

In [19]:
#slicing
arr1[1:4] # slice from index 1 to 3

array([2, 3, 4])

In [20]:
arr1[:3] # first 3 element

array([1, 2, 3])

In [23]:
arr1[::2] # every 2nd element

array([1, 3])

In [24]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

Slicing returns a view, not a copy! Changes affect the original array.**

This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

In [33]:
b = a[3:8] # b is not a copy but a view of a
b

array([4444,    5,    6,    7,    8])

In [34]:
b[0] = 4444

In [35]:
b

array([4444,    5,    6,    7,    8])

In [36]:
a

array([   1,    2,    3, 4444,    5,    6,    7,    8])

In [37]:
# to copy the numpy array we using .copy() function
c = a[3:8].copy()
c

array([4444,    5,    6,    7,    8])

In [38]:
c[0] = 12

In [39]:
c

array([12,  5,  6,  7,  8])

In [40]:
a

array([   1,    2,    3, 4444,    5,    6,    7,    8])

In [52]:
# fancy indexing (select multiple elements)
array = np.array([1,2,34,4,5])
idx = [0,2,4]
print(array[idx])
#or 
array[[2,4]]

[ 1 34  5]


array([34,  5])

In [54]:
# boolean masking (filter data)
mask = array > 25 # condition : value greater than 25
print(array[mask])
#or
array[array>3]

[34]


array([34,  4,  5])