In [1]:
import numpy as np

In [18]:
arr = np.array([1,2,3,4,5,6,2,3,4,5,])

In [19]:
np.mean(arr) #np.mean() – Compute the mean (average) of an array.

3.5

In [20]:
np.min(arr) #np.min() – Compute the minimum value of an array.

1

In [21]:
np.max(arr) #np.max() – Compute the maximum value of an array.

6

In [22]:
np.std(arr) #np.std() – Compute the standard deviation of an array.

1.5

In [23]:
np.var(arr) #np.var() – Compute the variance of an array.

2.25

In [24]:
np.sum(arr) #np.sum() – Compute the sum of all elements in an array.

35

In [25]:
np.prod(arr) #np.prod() – Compute the product of all elements in an array.

86400

In [26]:
np.percentile(arr,50) #np.percentile() – Compute the percentile of an array.
#For the 50th percentile (median)

3.5

In [27]:
np.argmin(arr) #np.argmin() – Return the index of the minimum value in an array.

0

In [28]:
np.argmax(arr) #np.argmax() – Return the index of the maximum value in an array.

5

In [29]:
np.unique(arr) #np.unique() – Find the unique elements of an array.

array([1, 2, 3, 4, 5, 6])

In [30]:
np.cumsum(arr) #np.cumsum() – Compute the cumulative sum of an array.

array([ 1,  3,  6, 10, 15, 21, 23, 26, 30, 35])

In [31]:
np.median(arr) #np.median() – Compute the median of an array.

3.5

In [32]:
arr1 = np.array([1,2,34,5,6])

np.corrcoef() – Compute the correlation coefficient matrix of two arrays.

np.corrcoef(arr1, arr2)

In [36]:
#np.diff() – Compute the n-th differences of an array.

np.diff(arr)

array([ 1,  1,  1,  1,  1, -4,  1,  1,  1])

In [37]:
#np.linspace() – Create an array with evenly spaced numbers over a specified interval.

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
#np.log() – Compute the natural logarithm of an array.

np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [39]:
#np.exp() – Compute the exponential of an array.

np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])