In [1]:
import numpy as np
import time

In [2]:
#zip function in python
L1 = [1,2,3]
L2 = [4,5,6]

list(zip(L1,L2))

[(1, 4), (2, 5), (3, 6)]

In [10]:
# addition of two lists using list

size = 1_000_000_00

a = list(range(size))
b = list(range(size))

start = time.time()

add = [x+y for x,y in zip(a,b)]

end = time.time()
print(add[0:10])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
10.60795521736145


In [11]:
# using numpy array

size = 1_000_000_00

a = np.array(list(range(size)))
b = np.array(list(range(size)))

start = time.time()

add = a + b

end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
3.194577932357788


In [12]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [17]:
# 2d array
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
type(arr)

numpy.ndarray

In [21]:
arr.shape
# (r,c) dimensions of the array

(2, 3)

In [23]:
#memory optimization 
import sys

list_data = list(range(1000))

numpy_data = np.array(list_data)

print("python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")

print("numpy array size:", numpy_data.nbytes, "bytes")

python list size: 8056000 bytes
numpy array size: 8000 bytes


In [25]:
#vectorization in numpy
list1 = [1,2,3,4]
arr1 = np.array([1,2,3,4])

start = time.time()
#python list loop
square_list = [x ** 2 for x in list1]
end = time.time()
print(end-start)
print(square_list)

start = time.time()
#numpy
numpy_square = arr1 ** 2
end = time.time()
print(end-start)
print(numpy_square)

0.001486063003540039
[1, 4, 9, 16]
0.00017523765563964844
[ 1  4  9 16]
